import React from 'react';
import { useStudyContext } from '../StudyContext';
import { Heading } from './ExerciseViews';
import { ContactLink } from './Controls';
import AppLink from './AppLink';
import site from '../../content/site.json';
// Terms of use: what the site is and is not, how the AI features may be used, the licence
// and the limits of liability. Plain language, no legalese the learner cannot follow.
export default function Terms() {
  const { t } = useStudyContext();
  const creator = site.creator?.name || null,
    email = site.creator?.email?.domain ? site.creator.email : null,
    github = site.creator?.github || null;
  return (
    <>
      <Heading
        title={t('Gebruiksvoorwaarden', 'Terms of use')}
        subtitle={t('Bijgewerkt op 10 september 2026', 'Updated 10 September 2026')}
      />
      <div className="privacy-document">
        <h2>{t('Wat deze site is', 'What this site is')}</h2>
        <p>
          {t(
            'Dit is een gratis, onafhankelijke oefensite voor de Nederlandse inburgeringsexamens, gemaakt door een particulier. De site heeft geen band met DUO, de Rijksoverheid of een exameninstantie en is geen officiële voorbereiding. Officiële informatie over de examens staat op inburgeren.nl.',
            'This is a free, independent practice site for the Dutch integration exams, made by a private individual. It has no connection with DUO, the Dutch government or any exam body and is not official preparation. Official information about the exams is on inburgeren.nl.',
          )}
        </p>
        <h2>{t('Oefenen, geen examen', 'Practice, not an exam')}</h2>
        <p>
          {t(
            'De opgaven zijn zelf geschreven en lijken op de examenonderdelen, maar zijn geen examenvragen en geen kopie ervan. De moeilijkheid is niet vastgesteld door een NT2-docent of een onderzoek met cursisten. Een score op deze site zegt niets over je kans om te slagen, en de site doet daar ook geen uitspraak over. Opgaven kunnen fouten bevatten; meld ze via Meld een probleem, dan worden ze nagekeken.',
            'The exercises are original, resemble the exam parts, but are not exam questions or copies of them. Their difficulty has not been established by an NT2 teacher or a learner study. A score here says nothing about your chance of passing, and the site makes no such claim. Exercises can contain mistakes; report them through Report a problem and they will be reviewed.',
          )}
        </p>
        <h2>{t('AI-feedback en spraakherkenning', 'AI feedback and speech recognition')}</h2>
        <p>
          {t(
            'De feedback op schrijf- en spreekopdrachten wordt gemaakt door een AI-taalmodel (OpenAI) en transcripties door spraakherkenning (ElevenLabs). Ze zijn een hulpmiddel bij het oefenen, geen beoordeling door een docent en geen examenuitslag. Ze kunnen fouten maken: een punt goed rekenen dat niet goed is, of andersom. Controleer je transcript voordat je feedback vraagt en lees de feedback kritisch. Luisterfragmenten gebruiken synthetische stemmen.',
            'Feedback on writing and speaking tasks is generated by an AI language model (OpenAI) and transcripts by speech recognition (ElevenLabs). They are aids for practice, not an assessment by a teacher and not an exam result. They can be wrong: marking a point as met when it is not, or the other way round. Check your transcript before requesting feedback and read the feedback critically. Listening clips use synthetic voices.',
          )}
        </p>
        <p>
          {t(
            'Deze diensten kosten geld per aanvraag. Daarom geldt een dagelijks maximum per browser en per netwerk, en kunnen ze tijdelijk uitstaan of pauzeren. Oefenen, nakijken met de antwoordsleutel en zelf nakijken werken altijd, ook zonder deze diensten.',
            'These services cost money per request. That is why there is a daily maximum per browser and per network, and why they can be switched off or paused for a while. Practising, checking with the answer key and self-review always work, also without these services.',
          )}
        </p>
        <h2>{t('Eerlijk gebruik', 'Fair use')}</h2>
        <p>
          {t(
            'Je mag de site vrij gebruiken om te oefenen. Niet toegestaan is: de AI-feedback of spraakherkenning aanroepen met scripts of buiten de site om, de limieten omzeilen, de site overbelasten, of persoonsgegevens van anderen invullen in een opmerking of antwoord. Bij misbruik kan de toegang voor een adres of sessie worden beperkt.',
            'You are free to use the site to practise. Not allowed: calling the AI feedback or speech recognition with scripts or outside the site, circumventing the limits, overloading the site, or entering other people’s personal data in a report or answer. Access for an address or session can be restricted in case of abuse.',
          )}
        </p>
        <h2>{t('Inhoud en licentie', 'Content and licence')}</h2>
        <p>
          {t(
            'De opgaven, de gegenereerde audio en illustraties en de programmatuur van deze site zijn open source onder de MIT-licentie',
            'The exercises, the generated audio and illustrations and the software of this site are open source under the MIT licence',
          )}
          {github ? (
            <>
              {' '}
              (
              <a href={github} rel="noreferrer">
                GitHub
              </a>
              )
            </>
          ) : null}
          {t(
            '. Je mag ze onder die licentie hergebruiken. Officieel examenmateriaal van DUO of andere partijen maakt geen deel uit van de site. De lettertypen vallen onder de SIL Open Font License.',
            '. You may reuse them under that licence. Official exam material from DUO or other parties is not part of the site. The typefaces are used under the SIL Open Font License.',
          )}
        </p>
        <h2>{t('Aansprakelijkheid', 'Liability')}</h2>
        <p>
          {t(
            'De site wordt aangeboden zoals hij is, zonder garantie op juistheid, volledigheid of beschikbaarheid. Voor zover de wet dat toelaat, is de maker niet aansprakelijk voor schade door het gebruik van de site, door fouten in opgaven of feedback, of doordat de site of een dienst tijdelijk niet werkt. Je bewaart je voortgang zelf in je browser; maak een export als je die niet wilt verliezen.',
            'The site is offered as is, without any guarantee of accuracy, completeness or availability. To the extent the law allows, the maker is not liable for damage arising from use of the site, from mistakes in exercises or feedback, or from the site or a service being unavailable. Your progress lives in your browser; export it if you do not want to lose it.',
          )}
        </p>
        <h2>{t('Recht en contact', 'Law and contact')}</h2>
        <p>
          {t(
            'Op deze voorwaarden is Nederlands recht van toepassing.',
            'Dutch law applies to these terms.',
          )}{' '}
          {creator
            ? t(`De site wordt beheerd door ${creator}.`, `The site is run by ${creator}.`)
            : null}{' '}
          {email ? (
            <>
              {t('Vragen: ', 'Questions: ')}
              <ContactLink email={email} label={t('stuur een e-mail', 'send an e-mail')} />.
            </>
          ) : null}{' '}
          {t('Hoe we met gegevens omgaan staat in de ', 'How we handle data is described in the ')}
          <AppLink to="privacy">{t('privacyverklaring', 'privacy notice')}</AppLink>.
        </p>
      </div>
    </>
  );
}
