// Shared vocabulary for authors, integration and learner-facing labels.
export const SKILLS = new Set([
  'detail',
  'time-place',
  'quantity',
  'person',
  'rule-application',
  'purpose',
  'advice',
  'sequence',
  'opinion',
  'inference',
  'summary',
  'picture',
]);
export const DOMAINS = {
  A2: new Set([
    'werk',
    'opleiding',
    'wonen-buurt',
    'gezondheid',
    'winkels-diensten',
    'instanties',
    'vervoer',
    'vrije-tijd-familie',
  ]),
  B1: new Set(['werk', 'educatie', 'overig']),
};
export const TASK_TYPES = {
  reading: {
    A2: ['brief', 'email', 'folder', 'bericht', 'advertentie', 'krant', 'regels', 'rooster'],
    B1: [
      'artikel',
      'interview',
      'studieboek',
      'website',
      'nieuwsbericht',
      'voorwaarden',
      'opzoektekst',
    ],
  },
  listening: {
    A2: ['gesprek', 'voicemail', 'omroep', 'nieuws', 'uitleg', 'reclame'],
    B1: ['interview', 'gesprek', 'voorlichting', 'instructie'],
  },
  writing: {
    A2: ['email', 'wijkkrant', 'form', 'picture-note'],
    B1: ['zinstaak', 'deelschrijftaak', 'korte-schrijftaak'],
  },
  speaking: {
    A2: ['video-answer', 'picture-describe', 'picture-choose', 'picture-sequence'],
    B1: ['kort', 'middellang'],
  },
  knm: { A2: ['feit'] },
};

export const TASK_LABELS: Record<string, [string, string]> = {
  email: ['E-mail', 'Email'],
  // Canonical task types (content/blueprint.md section 4).
  brief: ['Brief', 'Letter'],
  folder: ['Folder', 'Leaflet'],
  bericht: ['Bericht', 'Message'],
  advertentie: ['Advertentie', 'Advertisement'],
  krant: ['Krantenbericht', 'Newspaper item'],
  regels: ['Regels', 'Rules'],
  rooster: ['Rooster', 'Schedule'],
  gesprek: ['Gesprek', 'Conversation'],
  voicemail: ['Voicemail', 'Voicemail'],
  omroep: ['Omroepbericht', 'Announcement'],
  nieuws: ['Nieuwsbericht', 'News item'],
  uitleg: ['Uitleg', 'Explanation'],
  reclame: ['Reclame', 'Advertisement'],
  artikel: ['Artikel', 'Article'],
  interview: ['Interview', 'Interview'],
  studieboek: ['Studieboek', 'Textbook'],
  website: ['Website', 'Website'],
  nieuwsbericht: ['Nieuwsbericht', 'News item'],
  voorwaarden: ['Voorwaarden', 'Terms'],
  opzoektekst: ['Opzoektekst', 'Look-up text'],
  feit: ['Feit', 'Fact'],
  voorlichting: ['Voorlichting', 'Information session'],
  instructie: ['Instructie', 'Instructions'],
  wijkkrant: ['Wijkkrant', 'Neighbourhood newspaper'],
  form: ['Formulier', 'Form'],
  'picture-note': ['Briefje bij plaatjes', 'Picture-based note'],
  zinstaak: ['Zinstaak', 'Sentence task'],
  deelschrijftaak: ['Deelschrijftaak', 'Partial writing task'],
  'korte-schrijftaak': ['Korte schrijfopdracht', 'Short writing task'],
  'video-answer': ['Een vraag beantwoorden', 'Answer a question'],
  'picture-describe': ['Een plaatje beschrijven', 'Describe a picture'],
  'picture-choose': ['Een plaatje kiezen', 'Choose a picture'],
  'picture-sequence': ['Een reeks plaatjes beschrijven', 'Describe a picture sequence'],
  kort: ['Korte spreekopdracht', 'Short speaking task'],
  middellang: ['Middellange spreekopdracht', 'Medium speaking task'],
};
